harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
description: 'This is to verify CV integration with harness. '
envName: dev-canary
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - Lh9O151sSmC3_XapvUbb-w
- conditions:
  - SUCCESS
  - FAILED
  - PAUSED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - E9c-x3KdTsCLYgUyuHQqLg
phases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: COUNT
        instances: '2'
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: PROMETHEUS
      name: Prometheus
      properties:
        analysisServerConfigId: uJ0NZrvSTpCcC3PtWZf7HQ
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_CURRENT
        customThresholdRefId: 088d468e864c4969accf7868006b568c
        executeWithPreviousSteps: false
        includePreviousPhaseNodes: false
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeDuration: 5
        timeSeriesToAnalyze:
        - metricName: 'swap memory '
          metricType: INFRA
          txnName: infra
          url: container_cpu_usage_seconds_total{namespace="kaizen-canary",pod="$hostName",container="POD"}
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
      properties:
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    - type: APPROVAL
      name: Approval
      properties:
        approvalStateType: USER_GROUP
        timeoutMillis: 86400000
        userGroups:
        - E9c-x3KdTsCLYgUyuHQqLg
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
preDeploymentSteps:
- type: EMAIL
  name: Akash Gupta
  properties:
    body: 'Canary deployment trigger for ${app.name} - workflow: ${workflow.name}'
    ccAddress: manbir.bhullar@nationwide.co.uk
    subject: 'Canary deployment trigger for ${app.name} - workflow: ${workflow.name}'
    templateUuid: null
    templateVariables: null
    templateVersion: null
    toAddress: akash.gupta@nationwide.co.uk
rollbackPhases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster - Kaizen Testing Delegate
  daemonSet: false
  infraDefinitionName: dev -canary-infra
  name: Rollback Primary
  phaseNameForRollback: Primary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: canary-deploy-service
  statefulSet: false
templatized: false
